nelmio_api_doc:
    documentation:
        info:
            title: Efficient API
            description: API for the website Efficient
            version: 1.0.0
        security: false
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
